---
- name: Build inventory for Workshop Lab systems
  hosts: localhost
  gather_facts: false
  vars:
    ec2_exact_count: 1
    ec2_vpcidr: 10.251.0.0/16
    ec2_subnetcidr: 10.251.1.0/24
    ec2_az: a
    ec2_region: us-east-1
    ec2_stack_name: labStack
    ec2_key_name: secretKeyName
    resource_requester: admin
    
  tasks:
  
  - name: Build group of instances
    add_host:
      name: "{{ item.public_dns_name }}"
      groups: labservers
      ansible_user: ec2-user
      ansible_host: "{{ item.public_ip }}"
    with_items: "{{ instances }}"
    when: instance_source is search ('ec2')

- name: Configure Workshop Lab systems
  hosts: labservers
  gather_facts: false
  vars:
    
  tasks:
  
  - name: Update system
    yum:
      state: latest
      name: '*'
    
  - name: Install lab packages
    yum:
      state: present
      name:
        - httpd
        - python-firewall
        - firewalld
    
  - name: Configure labs
    service:
      name: httpd
      state: started
      enabled: true
      
  - name: Configure system firewall
    firewalld:
      service: http
      permanent: true
      state: enabled
      
  - name: Configure system firewall for HTTPS
    firewalld:
      service: https
      permanent: true
      state: enabled
      
  - name: Restart the firewalld service to load in the firewall changes
    service: 
      name: firewalld 
      state: restarted
    
  - name: Ansible Tower Workflow Pass
    set_stats:
      data:
        labserver_endpoint: "http://{{ instances[0].public_dns_name }}"
